/**
 * Pulls every model in the manifest from Sketchfab, optimises it into
 * `public/models`, and regenerates the attribution the UI renders.
 *
 *   npm run models:sync                 # fetch anything missing
 *   npm run models:sync -- ls-v8        # just one
 *   npm run models:sync -- --force      # re-fetch everything
 *
 * Optimised models are committed to the repo, so a normal install and build
 * never touches the network or needs an API token. This runs when the manifest
 * gains an entry, and otherwise not at all.
 */

import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join as joinPath } from "node:path";
import { fileURLToPath } from "node:url";
import {
  MODEL_MANIFEST,
  type ModelManifestEntry,
} from "./modelManifest";
import {
  describeGlb,
  optimizeGlbForWeb,
  type OptimizeGlbResult,
} from "./optimizeGlb";
import {
  downloadToFile,
  fetchModelMetadata,
  resolveGlbDownloadUrl,
  type SketchfabModelMetadata,
} from "./sketchfabClient";

const PROJECT_ROOT = joinPath(dirname(fileURLToPath(import.meta.url)), "..");
const SHIPPED_MODELS_DIR = joinPath(PROJECT_ROOT, "public", "models");
const RAW_DOWNLOADS_DIR = joinPath(PROJECT_ROOT, ".model-downloads");
const CREDITS_FILE = joinPath(
  PROJECT_ROOT,
  "content",
  "generated",
  "modelCredits.ts",
);
const CREDITS_MARKDOWN = joinPath(PROJECT_ROOT, "CREDITS.md");

type SyncedModel = {
  entry: ModelManifestEntry;
  metadata: SketchfabModelMetadata;
  optimization: OptimizeGlbResult;
};

function loadEnvFromWorkspaceRoot(): void {
  // The token lives one level up, beside the raw asset downloads, so it is
  // shared by anything else in the 3d workspace that needs Sketchfab.
  for (const candidate of [
    joinPath(PROJECT_ROOT, ".env"),
    joinPath(PROJECT_ROOT, "..", ".env"),
  ]) {
    if (existsSync(candidate)) process.loadEnvFile(candidate);
  }
}

function formatBytes(bytes: number): string {
  return bytes >= 1_000_000
    ? `${(bytes / 1_000_000).toFixed(2)} MB`
    : `${Math.round(bytes / 1000)} KB`;
}

async function syncOneModel(
  entry: ModelManifestEntry,
): Promise<SyncedModel> {
  const metadata = await fetchModelMetadata(entry.sketchfabUid);
  console.log(`  source     ${metadata.name} — ${metadata.authorName}`);
  console.log(`  license    ${metadata.licenseLabel}`);

  const rawPath = joinPath(RAW_DOWNLOADS_DIR, `${entry.slug}.raw.glb`);
  const shippedPath = joinPath(SHIPPED_MODELS_DIR, `${entry.slug}.glb`);

  if (!existsSync(rawPath)) {
    const downloadUrl = await resolveGlbDownloadUrl(entry.sketchfabUid);
    await downloadToFile(downloadUrl, rawPath);
  }

  const optimization = await optimizeGlbForWeb({
    inputPath: rawPath,
    outputPath: shippedPath,
    triangleBudget: entry.triangleBudget,
    hasNamedPartMeshes: entry.hasNamedPartMeshes ?? false,
    simplifyError: entry.simplifyError,
  });

  const { triangleCountBefore, triangleCountAfter, byteSizeBefore, byteSizeAfter } =
    optimization;
  console.log(
    `  triangles  ${triangleCountBefore.toLocaleString()} → ${triangleCountAfter.toLocaleString()}`,
  );
  console.log(
    `  size       ${formatBytes(byteSizeBefore)} → ${formatBytes(byteSizeAfter)}`,
  );

  if (optimization.partMeshNames.length > 0) {
    console.log(`  meshes     ${optimization.partMeshNames.join(", ")}`);
  }

  return { entry, metadata, optimization };
}

function renderCreditsModule(synced: SyncedModel[]): string {
  const entries = synced
    .map(({ entry, metadata, optimization }) => {
      const credit = {
        slug: entry.slug,
        sourceName: metadata.name,
        authorName: metadata.authorName,
        authorProfileUrl: metadata.authorProfileUrl,
        modelPageUrl: metadata.modelPageUrl,
        licenseLabel: metadata.licenseLabel,
        sourceTriangleCount: optimization.triangleCountBefore,
        shippedTriangleCount: optimization.triangleCountAfter,
        shippedByteSize: optimization.byteSizeAfter,
      };
      return `  "${entry.slug}": ${JSON.stringify(credit, null, 4)
        .split("\n")
        .join("\n  ")},`;
    })
    .join("\n");

  return `// GENERATED by \`npm run models:sync\` — do not edit by hand.
// Source of truth is scripts/modelManifest.ts.

import type { ModelCredit } from "../types";

export const MODEL_CREDITS: Record<string, ModelCredit> = {
${entries}
};
`;
}

/**
 * The attribution page, written from the same data the app reads.
 *
 * Kept generated rather than hand-maintained because it is exactly the file
 * that rots: every model added is a licence someone has to remember to record,
 * and the consequence of forgetting is not a broken build but an uncredited
 * artist.
 */
function renderCreditsMarkdown(synced: SyncedModel[]): string {
  const rows = synced
    .map(({ entry, metadata, optimization }) => {
      const reduction =
        optimization.triangleCountBefore > optimization.triangleCountAfter
          ? ` (decimated from ${optimization.triangleCountBefore.toLocaleString()})`
          : "";
      return [
        `### ${metadata.name}`,
        ``,
        `| | |`,
        `| --- | --- |`,
        `| Used as | \`${entry.slug}\` |`,
        `| Author | [${metadata.authorName}](${metadata.authorProfileUrl}) |`,
        `| Source | <${metadata.modelPageUrl}> |`,
        `| License | Sketchfab **${metadata.licenseLabel}** |`,
        `| As shipped | ${optimization.triangleCountAfter.toLocaleString()} triangles${reduction} · ${formatBytes(optimization.byteSizeAfter)} |`,
        ``,
      ].join("\n");
    })
    .join("\n");

  return `<!-- GENERATED by \`npm run models:sync\` — do not edit by hand. -->
<!-- Source of truth is scripts/modelManifest.ts. -->

# Credits

The 3D assets in this project are **licensed, not self-modelled**. What was
built here is the interactive layer around them: the callout system, the
snapping and occlusion logic, the camera work, the section cut, the quiz, the
palette, and the content.

Every model below is used within the terms of its licence. Sketchfab's licences
permit use in derivative works and inside applications; they prohibit
redistributing or reselling the model itself as a standalone asset. This project
embeds them in an application rather than offering them for download, which is
within those terms. Licence text: <https://sketchfab.com/licenses>

## Models

${rows}
## What was changed about the assets

No modelling or sculpting was done. Each source file is processed by
\`npm run models:sync\` using [glTF-Transform](https://gltf-transform.dev):
deduplicated, flattened, welded, decimated to a per-model triangle budget where
it exceeded one, merged into a single mesh where its own mesh names carried no
information, and finally compressed with Meshopt at \`level: "high"\`.

The models arrive untextured or have their textures discarded — the app applies
one \`MeshStandardMaterial\` at runtime and lights it with \`<Lightformer>\`
panels rather than an HDR file, so the app fetches no third-party assets at
runtime.

## Fonts

- **Archivo** and **IBM Plex Mono**, both served self-hosted via \`next/font\`
  (SIL Open Font License 1.1).
`;
}

async function main(): Promise<void> {
  loadEnvFromWorkspaceRoot();

  const args = process.argv.slice(2);
  const force = args.includes("--force");
  const requestedSlugs = args.filter((arg) => !arg.startsWith("--"));

  mkdirSync(SHIPPED_MODELS_DIR, { recursive: true });
  mkdirSync(RAW_DOWNLOADS_DIR, { recursive: true });
  mkdirSync(dirname(CREDITS_FILE), { recursive: true });

  const selected = requestedSlugs.length
    ? MODEL_MANIFEST.filter((entry) => requestedSlugs.includes(entry.slug))
    : MODEL_MANIFEST;

  if (selected.length === 0) {
    throw new Error(
      `No manifest entry matched ${requestedSlugs.join(", ")}. Known slugs: ` +
        MODEL_MANIFEST.map((entry) => entry.slug).join(", "),
    );
  }

  const synced: SyncedModel[] = [];

  for (const entry of selected) {
    const shippedPath = joinPath(SHIPPED_MODELS_DIR, `${entry.slug}.glb`);
    const alreadyShipped = existsSync(shippedPath);

    console.log(`\n${entry.slug}`);
    if (alreadyShipped && !force) {
      // Still fetch metadata: it is what regenerates the credits file, and it
      // is one cheap request against a model we already have on disk.
      const metadata = await fetchModelMetadata(entry.sketchfabUid);
      console.log(`  up to date (--force to re-fetch)`);
      synced.push({
        entry,
        metadata,
        optimization: await describeShippedModel(shippedPath, metadata),
      });
      continue;
    }

    synced.push(await syncOneModel(entry));
  }

  // Credits must describe every model the app can load, not just the ones this
  // run touched, or a single-slug sync would silently delete the others.
  if (requestedSlugs.length === 0) {
    writeFileSync(CREDITS_FILE, renderCreditsModule(synced));
    writeFileSync(CREDITS_MARKDOWN, renderCreditsMarkdown(synced));
    console.log(`\nWrote ${CREDITS_FILE}`);
    console.log(`Wrote ${CREDITS_MARKDOWN}`);
  } else {
    console.log(
      `\nSkipped rewriting credits — run without a slug filter to regenerate them.`,
    );
  }

  if (existsSync(RAW_DOWNLOADS_DIR) && process.env.KEEP_RAW_DOWNLOADS !== "1") {
    rmSync(RAW_DOWNLOADS_DIR, { recursive: true, force: true });
  }
}

/**
 * Stats for a model optimised on a previous run. The shipped counts are read
 * back off the file rather than assumed, so the credits stay true even for
 * models this run did not rebuild.
 */
async function describeShippedModel(
  shippedPath: string,
  metadata: SketchfabModelMetadata,
): Promise<OptimizeGlbResult> {
  const shipped = await describeGlb(shippedPath);
  return {
    triangleCountBefore: metadata.sourceTriangleCount,
    triangleCountAfter: shipped.triangleCount,
    byteSizeBefore: 0,
    byteSizeAfter: shipped.byteSize,
    meshCountAfter: shipped.meshCount,
    partMeshNames: shipped.meshNodeNames,
  };
}

main().catch((error) => {
  console.error(`\n${error instanceof Error ? error.message : error}`);
  process.exitCode = 1;
});
